services:
    twig.extension.intl:
           class: Twig_Extensions_Extension_Intl
           tags:
               - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags: [ { name: 'twig.extension' } ]

    hb_sendNewsletter:
        class: HB\HyperbricoBundle\SendNewsletter\HBSendNewsletter
        arguments: [@swiftmailer.mailer.default, @doctrine.orm.entity_manager, @templating, @form.csrf_provider, %mailer_user%, %secret%, %mail_brico%, %username_gifi%, %password_gifi%]

