imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

doctrine:
    orm:
        query_cache_driver:    apc
        metadata_cache_driver: apc

monolog:
    handlers:
        main:
            type:               fingers_crossed
            action_level:       critical
            handler:            grouped
        grouped:
            type:               group
            members:            [streamed, swift]
        streamed:
            type:               stream
            path:               "%kernel.logs_dir%/%kernel.environment%.log"
            level:              debug
        swift:
            type:               swift_mailer
            from_email:         %mailer_user%
            to_email:           beaumont.cedric@gmail.com
            subject:            "Error HYPER BRICO"
            level:              debug
        login:
            type:               stream
            path:               "%kernel.logs_dir%/auth.log"
            level:              info
            channels:           security
