<?php

namespace HB\HyperbricoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogueRepository extends EntityRepository
{
    public function findCataloguePubliable($type)
    {
        $query = $this->createQueryBuilder('n')
                      ->where('CURRENT_DATE() BETWEEN n.datePubDebut AND n.datePubFin')
                      ->orderBy('n.datePubDebut', 'DESC')
                      ->andWhere('n.type = :type')
                      ->setParameter('type', $type);

        return $query->getQuery()->getResult();
    }

    public function findDernierCataloguePubliable($type)
    {
        $query = $this->createQueryBuilder('n')
                      ->where('CURRENT_DATE() BETWEEN n.datePubDebut AND n.datePubFin')
                      ->orderBy('n.datePubDebut', 'DESC')
                      ->setFirstResult(0)
                      ->setMaxResults(1)
                      ->andWhere('n.type = :type')
                      ->setParameter('type', $type);

        return $query->getQuery()->getResult();
    }

    public function findAncienCatalogue($type)
    {
      $query = $this->createQueryBuilder('n')
                      ->where('n.datePubFin < CURRENT_DATE()')
                      ->orderBy('n.datePubDebut', 'DESC')
                      ->andWhere('n.type = :type')
                      ->setParameter('type', $type);
                      
        return $query->getQuery()->getResult();
    }
}
