<?php

namespace HB\HyperbricoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
	public function countCommandes()
	{
		$query = $this->createQueryBuilder('n')
                      ->select('count(n)');

        return $query->getQuery()->getSingleScalarResult();
	}
}
