<?php

namespace HB\HyperbricoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findNewsPubliable()
    {
        $query = $this->createQueryBuilder('n')
                      ->where('CURRENT_DATE() BETWEEN n.datePubDebut AND n.datePubFin')
                      ->orderBy('n.datePubDebut', 'DESC');

        return $query->getQuery()->getResult();
    }

    public function findAncienneNews()
    {
      $query = $this->createQueryBuilder('n')
                      ->where('n.datePubFin < CURRENT_DATE()')
                      ->orderBy('n.datePubDebut', 'DESC');

        return $query->getQuery()->getResult();
    }
}
